# Generated by Django 4.0.5 on 2022-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='uploads/songs/'),
        ),
    ]
